add_rules("mode.debug", "mode.release")

target("sort")
    set_kind("static")
    add_cflags("-std=c23")
    add_files("src/sort/*.c")
    add_includedirs("src/sort", {public = true})

target("heap")
    set_kind("static")
    add_cflags("-std=c23")
    add_files("src/heap/*.c")
    add_includedirs("src/heap", {public = true})

target("huffman")
    set_kind("static")
    add_cflags("-std=c23")
    add_files("src/huffman/*.c")
    add_deps("heap")
    add_includedirs("src/huffman", {public = true})

target("sort_test")
    set_kind("binary")
    add_cflags("-std=c23")
    add_files("test/sort_test.c")
    add_deps("sort")
    set_default()

target("heap_test")
    set_kind("binary")
    add_cflags("-std=c23")
    add_files("test/heap_test.c")
    add_deps("heap")

target("huffman_test")
    set_kind("binary")
    add_cflags("-std=c23")
    add_files("test/huffman_test.c")
    add_deps("huffman")
